import type { Metadata } from "next";
import { Geist, Geist_Mono, Raleway } from "next/font/google";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const raleway = Raleway({
  weight: ["400", "300", "100", "700", "900"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.className} min-h-screen scroll-smooth scroll-pt-40 overflow-y-scroll bg-background`}
      >
        {children}
      </body>
    </html>
  );
}
